# AI-Author: Codex (OpenAI model not exposed by runtime)
{{- range $component := list "controller" "api" "console" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-guardrail-{{ $component }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "network-guardrail.labels" $ | nindent 4 }}
{{- end }}
{{- if .Values.collector.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-guardrail-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "network-guardrail.labels" . | nindent 4 }}
{{- end }}
